packages:
  - ./spec
  - ./polyfill
  - ./codemod
  - ./utils
  - ./examples/*

  - ./misc/export-size
  - ./misc/terser

  # - ./misc/datetimeformat-tokens
  # - ./misc/durationformat-polyfill
  # - ./misc/locale-data
  # - ./misc/locale-textinfo
  # - ./misc/locale-weekinfo
