#!/usr/bin/env node

/*
Generates RESULTS.md, comparing the gzipped bundle size of this package's
global IIFE builds against @js-temporal/polyfill's global UMD build.

Our builds are read from the pre-minified `.global.min.js` outputs (run
`pnpm run minify` to generate them). The competitor's UMD bundle is minified
here with the same Terser config, so the numbers are apples-to-apples.
*/

import { existsSync } from 'fs'
import { dirname, join as joinPaths } from 'path'
import { fileURLToPath } from 'url'
import { readFile, writeFile } from 'fs/promises'
import { gzipSizeSync } from 'gzip-size'
import { minify as minifyWithTerser } from 'terser'
import { buildTerserMinifyOptions } from '../lib/minify-options.js'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const pkgDir = joinPaths(scriptDir, '../..') // the `polyfill` package root
const resultsPath = joinPaths(scriptDir, 'RESULTS.md')

const COMPETITOR = '@js-temporal/polyfill'

// Our two pre-minified global IIFE builds. `basic` ships only the ISO
// calendar; `full` bundles every calendar. The competitor has no such split.
const OUR_BUILDS = [
  { label: 'Basic calendars', minPath: 'dist/.global.min.js' },
  { label: 'All calendars', minPath: 'dist/full/.global.min.js' },
]

run()

async function run() {
  // Read + gzip each of our pre-built minified bundles.
  const ours = []
  for (const { label, minPath } of OUR_BUILDS) {
    const absPath = joinPaths(pkgDir, minPath)
    if (!existsSync(absPath)) {
      throw new Error(
        `Missing ${minPath}. Run \`pnpm run minify\` to generate the minified bundles first.`,
      )
    }
    const code = await readFile(absPath, 'utf-8')
    ours.push({ label, gzipped: gzipSizeSync(code) })
  }

  // Resolve the competitor's latest published version + CDN URL, so the
  // comparison tracks their newest release without manual edits.
  const version = await fetchLatestVersion(COMPETITOR)
  const competitorUrl = `https://cdn.jsdelivr.net/npm/${COMPETITOR}@${version}/dist/index.umd.js`

  // @js-temporal/polyfill ships a single UMD bundle that always includes all
  // calendars, so its size is compared against both of our builds.
  const competitorCode = await fetchText(competitorUrl)
  const competitorGzipped = await minzippedSize(competitorCode)

  await writeFile(
    resultsPath,
    renderMarkdown({ version, competitorUrl, ours, competitorGzipped }),
  )
  console.log(`Wrote ${resultsPath}`)
}

// Minify with the package's Terser defaults, then gzip; returns byte count.
async function minzippedSize(code) {
  const { code: minified } = await minifyWithTerser(
    code,
    buildTerserMinifyOptions(),
  )
  return gzipSizeSync(minified)
}

async function fetchLatestVersion(pkg) {
  const data = await fetchJson(`https://registry.npmjs.org/${pkg}/latest`)
  return data.version
}

function renderMarkdown({ version, competitorUrl, ours, competitorGzipped }) {
  // Build the comparison row: competitor size shown in each column with how
  // much larger it is than the corresponding `temporal-polyfill` build.
  const competitorCells = ours.map(({ gzipped }) => {
    const diff = Math.round((competitorGzipped / gzipped - 1) * 100)
    return `${formatBytes(competitorGzipped)} (+${diff}%)`
  })

  return `# Bundle size comparison

> Auto-generated by \`node ./run.js\`

Gzipped size of [\`temporal-polyfill\`](https://www.npmjs.com/package/temporal-polyfill)'s
global IIFE builds versus [\`${COMPETITOR}\`](${competitorUrl})'s global UMD build (v${version}).
All bundles are minified with Terser, then gzipped.

| Package | ${ours.map((b) => b.label).join(' | ')} |
| --- | ${ours.map(() => '---:').join(' | ')} |
| \`temporal-polyfill\` | ${ours.map((b) => formatBytes(b.gzipped)).join(' | ')} |
| \`${COMPETITOR}\` | ${competitorCells.join(' | ')} |

\`${COMPETITOR}\` has no basic/full split — its single bundle always includes
every calendar, so the same size appears in both columns.
`
}

function formatBytes(bytes) {
  return `${bytes.toLocaleString('en-US')} B`
}

async function fetchJson(url) {
  return JSON.parse(await fetchText(url))
}

async function fetchText(url) {
  const res = await fetch(url)
  if (!res.ok) {
    throw new Error(`Failed to fetch ${url}: ${res.status} ${res.statusText}`)
  }
  return res.text()
}
