export type FnsCodemodStatus =
  | 'direct'
  | 'temporal-utils'
  | 'contextual-calendar'
  | 'diagnostic-only'

export type FnsApiCoverage = Record<string, Record<string, FnsCodemodStatus>>

const dateCalendarFields = {
  dayOfWeek: 'direct',
  daysInWeek: 'direct',
  weekOfYear: 'direct',
  yearOfWeek: 'direct',
  dayOfYear: 'direct',
  daysInMonth: 'direct',
  daysInYear: 'direct',
  monthsInYear: 'direct',
  inLeapYear: 'direct',
} as const satisfies Record<string, FnsCodemodStatus>

const dateUnitArithmetic = {
  add: 'direct',
  addYears: 'direct',
  addMonths: 'direct',
  addWeeks: 'direct',
  addDays: 'direct',
  subtract: 'direct',
  subtractYears: 'direct',
  subtractMonths: 'direct',
  subtractWeeks: 'direct',
  subtractDays: 'direct',
} as const satisfies Record<string, FnsCodemodStatus>

const timeUnitArithmetic = {
  addHours: 'direct',
  addMinutes: 'direct',
  addSeconds: 'direct',
  addMilliseconds: 'direct',
  addMicroseconds: 'direct',
  addNanoseconds: 'direct',
  subtractHours: 'direct',
  subtractMinutes: 'direct',
  subtractSeconds: 'direct',
  subtractMilliseconds: 'direct',
  subtractMicroseconds: 'direct',
  subtractNanoseconds: 'direct',
} as const satisfies Record<string, FnsCodemodStatus>

const dateUnitDiffs = {
  diff: 'direct',
  diffYears: 'temporal-utils',
  diffMonths: 'temporal-utils',
  diffWeeks: 'temporal-utils',
  diffDays: 'temporal-utils',
} as const satisfies Record<string, FnsCodemodStatus>

const timeUnitDiffs = {
  diffHours: 'temporal-utils',
  diffMinutes: 'temporal-utils',
  diffSeconds: 'temporal-utils',
  diffMilliseconds: 'temporal-utils',
  diffMicroseconds: 'temporal-utils',
  diffNanoseconds: 'temporal-utils',
} as const satisfies Record<string, FnsCodemodStatus>

const dateRounds = {
  roundToYear: 'temporal-utils',
  roundToMonth: 'temporal-utils',
  roundToWeek: 'temporal-utils',
} as const satisfies Record<string, FnsCodemodStatus>

const timeRounds = {
  roundToHour: 'temporal-utils',
  roundToMinute: 'temporal-utils',
  roundToSecond: 'temporal-utils',
  roundToMillisecond: 'temporal-utils',
  roundToMicrosecond: 'temporal-utils',
} as const satisfies Record<string, FnsCodemodStatus>

const dateStartsAndEnds = {
  startOfYear: 'temporal-utils',
  startOfMonth: 'temporal-utils',
  startOfWeek: 'temporal-utils',
  endOfYear: 'temporal-utils',
  endOfMonth: 'temporal-utils',
  endOfWeek: 'temporal-utils',
} as const satisfies Record<string, FnsCodemodStatus>

const timeStartsAndEnds = {
  startOfHour: 'temporal-utils',
  startOfMinute: 'temporal-utils',
  startOfSecond: 'temporal-utils',
  startOfMillisecond: 'temporal-utils',
  startOfMicrosecond: 'temporal-utils',
  endOfHour: 'temporal-utils',
  endOfMinute: 'temporal-utils',
  endOfSecond: 'temporal-utils',
  endOfMillisecond: 'temporal-utils',
  endOfMicrosecond: 'temporal-utils',
} as const satisfies Record<string, FnsCodemodStatus>

const dateFieldReplacement = {
  withDayOfYear: 'temporal-utils',
  withDayOfMonth: 'temporal-utils',
  withDayOfWeek: 'temporal-utils',
  withWeekOfYear: 'temporal-utils',
} as const satisfies Record<string, FnsCodemodStatus>

const formatting = {
  toString: 'direct',
  toBasicString: 'direct',
  toLocaleString: 'direct',
  createFormat: 'diagnostic-only',
} as const satisfies Record<string, FnsCodemodStatus>

const nativeConversion = {
  toNative: 'direct',
} as const satisfies Record<string, FnsCodemodStatus>

export const fnsApiCoverage = {
  Calendar: {
    getBasic: 'contextual-calendar',
    getExotic: 'contextual-calendar',
    getAny: 'contextual-calendar',
    getISO: 'contextual-calendar',
    getGregory: 'contextual-calendar',
    getBuddhist: 'contextual-calendar',
    getChinese: 'contextual-calendar',
    getDangi: 'contextual-calendar',
    getCoptic: 'contextual-calendar',
    getEthiopic: 'contextual-calendar',
    getEthiopicAmeteAlem: 'contextual-calendar',
    getHebrew: 'contextual-calendar',
    getIndian: 'contextual-calendar',
    getJapanese: 'contextual-calendar',
    getIslamicCivil: 'contextual-calendar',
    getIslamicTabular: 'contextual-calendar',
    getIslamicUmmAlQura: 'contextual-calendar',
    getPersian: 'contextual-calendar',
    getRoc: 'contextual-calendar',
  },
  Instant: {
    isRecord: 'direct',
    create: 'direct',
    fromEpochMilliseconds: 'direct',
    fromEpochNanoseconds: 'direct',
    fromString: 'direct',
    add: 'direct',
    ...timeUnitArithmetic,
    subtract: 'direct',
    diff: 'direct',
    ...timeUnitDiffs,
    equals: 'direct',
    compare: 'direct',
    ...timeRounds,
    toZonedDateTimeISO: 'direct',
    ...formatting,
    ...nativeConversion,
  },
  ZonedDateTime: {
    isRecord: 'direct',
    create: 'direct',
    fromFields: 'direct',
    fromString: 'direct',
    offsetNanoseconds: 'direct',
    offset: 'direct',
    ...dateCalendarFields,
    hoursInDay: 'direct',
    withFields: 'direct',
    withCalendar: 'direct',
    withTimeZone: 'direct',
    withPlainTime: 'direct',
    ...dateFieldReplacement,
    ...dateUnitArithmetic,
    ...timeUnitArithmetic,
    ...dateUnitDiffs,
    ...timeUnitDiffs,
    equals: 'direct',
    compare: 'direct',
    ...dateRounds,
    roundToDay: 'temporal-utils',
    ...timeRounds,
    ...dateStartsAndEnds,
    startOfDay: 'direct',
    ...timeStartsAndEnds,
    endOfDay: 'temporal-utils',
    getTimeZoneTransition: 'direct',
    toInstant: 'direct',
    toPlainDateTime: 'direct',
    toPlainDate: 'direct',
    toPlainTime: 'direct',
    ...formatting,
    ...nativeConversion,
  },
  PlainDateTime: {
    isRecord: 'direct',
    create: 'direct',
    fromFields: 'direct',
    fromString: 'direct',
    ...dateCalendarFields,
    withCalendar: 'direct',
    withFields: 'direct',
    withPlainTime: 'direct',
    ...dateFieldReplacement,
    ...dateUnitArithmetic,
    ...timeUnitArithmetic,
    ...dateUnitDiffs,
    ...timeUnitDiffs,
    equals: 'direct',
    compare: 'direct',
    ...dateRounds,
    roundToDay: 'temporal-utils',
    ...timeRounds,
    ...dateStartsAndEnds,
    startOfDay: 'temporal-utils',
    ...timeStartsAndEnds,
    endOfDay: 'temporal-utils',
    toZonedDateTime: 'direct',
    toPlainDate: 'direct',
    toPlainTime: 'direct',
    ...formatting,
    ...nativeConversion,
  },
  PlainDate: {
    isRecord: 'direct',
    create: 'direct',
    fromFields: 'direct',
    fromString: 'direct',
    ...dateCalendarFields,
    withFields: 'direct',
    withCalendar: 'direct',
    ...dateFieldReplacement,
    ...dateUnitArithmetic,
    ...dateUnitDiffs,
    equals: 'direct',
    compare: 'direct',
    ...dateRounds,
    ...dateStartsAndEnds,
    toZonedDateTime: 'direct',
    toPlainDateTime: 'direct',
    toPlainYearMonth: 'direct',
    toPlainMonthDay: 'direct',
    ...formatting,
    ...nativeConversion,
  },
  PlainTime: {
    isRecord: 'direct',
    create: 'direct',
    fromFields: 'direct',
    fromString: 'direct',
    withFields: 'direct',
    add: 'direct',
    ...timeUnitArithmetic,
    subtract: 'direct',
    diff: 'direct',
    ...timeUnitDiffs,
    equals: 'direct',
    compare: 'direct',
    ...timeRounds,
    ...timeStartsAndEnds,
    ...formatting,
    ...nativeConversion,
  },
  PlainYearMonth: {
    isRecord: 'direct',
    create: 'direct',
    fromFields: 'direct',
    fromString: 'direct',
    daysInMonth: 'direct',
    daysInYear: 'direct',
    monthsInYear: 'direct',
    inLeapYear: 'direct',
    withFields: 'direct',
    add: 'direct',
    addYears: 'direct',
    addMonths: 'direct',
    subtract: 'direct',
    subtractYears: 'direct',
    subtractMonths: 'direct',
    diff: 'direct',
    diffYears: 'temporal-utils',
    diffMonths: 'temporal-utils',
    equals: 'direct',
    compare: 'direct',
    roundToYear: 'temporal-utils',
    startOfYear: 'temporal-utils',
    endOfYear: 'temporal-utils',
    toPlainDate: 'direct',
    ...formatting,
    ...nativeConversion,
  },
  PlainMonthDay: {
    isRecord: 'direct',
    create: 'direct',
    fromFields: 'direct',
    fromString: 'direct',
    withFields: 'direct',
    equals: 'direct',
    toPlainDate: 'direct',
    ...formatting,
    ...nativeConversion,
  },
  Duration: {
    isRecord: 'direct',
    create: 'direct',
    fromFields: 'direct',
    fromString: 'direct',
    sign: 'direct',
    blank: 'direct',
    withFields: 'direct',
    negated: 'direct',
    abs: 'direct',
    add: 'direct',
    subtract: 'direct',
    round: 'direct',
    total: 'direct',
    compare: 'direct',
    toString: 'direct',
    toBasicString: 'direct',
    toLocaleString: 'direct',
    ...nativeConversion,
  },
  Now: {
    timeZoneId: 'direct',
    instant: 'direct',
    zonedDateTimeISO: 'direct',
    plainDateTimeISO: 'direct',
    plainDateISO: 'direct',
    plainTimeISO: 'direct',
  },
} as const satisfies FnsApiCoverage
