
name: CI

on:
  push:
    branches:
      - spec-stage-4-ci

env:
  TZ: "America/New_York"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        TEST_NODE_VERSION: [16.20.0, 18.19.0, 20.10.0, 22.14.0, 24.16.0, 26.2.0]
        include:
          - TEST_NODE_VERSION: 16.20.0
            TEST262_CLASS_API: full
            LINTING: 1
            VITEST: 0
          - TEST_NODE_VERSION: 18.19.0
            TEST262_CLASS_API: full
          - TEST_NODE_VERSION: 20.10.0
            TEST262_CLASS_API: full
            TEST262_MINIFIER: terser
          - TEST_NODE_VERSION: 22.14.0
            TEST262_CLASS_API: full
            TEST262_MINIFIER: terser
          - TEST_NODE_VERSION: 24.16.0
            TEST262_CLASS_API: full
            TEST262_MINIFIER: terser
            TEST262_FORCE_SHIM: 1
          - TEST_NODE_VERSION: 26.2.0
            TEST262_CLASS_API: full
            TEST262_MINIFIER: terser
            TEST262_FORCE_SHIM: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.20.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          # NOTE: keep synced with .npmrc
          node-version: 22.14.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        if: matrix.LINTING
        run: pnpm run lint

      - name: Build
        run: >
          TEST262_CLASS_API=${{ matrix.TEST262_CLASS_API }}
          TEST262_MINIFIER=${{ matrix.TEST262_MINIFIER }}
          TEST262_FORCE_SHIM=${{ matrix.TEST262_FORCE_SHIM }}
          pnpm run build

      # temporal-polyfill vitest requires temporal-utils to be built
      - name: Vitest
        if: matrix.VITEST != 0
        run: >
          TEST_NODE_VERSION=${{ matrix.TEST_NODE_VERSION }}
          pnpm run vitest

      - name: Test 262
        run: >
          TEST_NODE_VERSION=${{ matrix.TEST_NODE_VERSION }}
          TEST262_MINIFIER=${{ matrix.TEST262_MINIFIER }}
          pnpm run test262
