
name: CI

on:
  push:
    branches:
      - main

env:
  TZ: "America/New_York"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [14.21.3, 16.20.0, 18.19.0, 20.10.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          # NOTE: keep synced with .npmrc
          node-version: 18.19.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        # Only for the first Node version
        if: matrix.node == '14.21.3'
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Test
        run: TEST262_NODE_VERSION=${{ matrix.node }} pnpm run test
